# Accesstoken - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTE0Mzc1ODU2NjhkNzBlMThjZTVlMCIsImlhdCI6MTcyMDc5NjAyMX0.klo7x2048r6xUs7n5bydwuGKOYp7A1LVoIiKbbhpmN4

# POST http://localhost:3000/signup
# Content-Type:  application/json

# {
#     "fullname": "john",
#     "email": "john2@gmail.com",
#     "password": "John@123"
# }

POST http://localhost:3000/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTE0Mzc1ODU2NjhkNzBlMThjZTVlMCIsImlhdCI6MTcyMDc5NjAyMX0.klo7x2048r6xUs7n5bydwuGKOYp7A1LVoIiKbbhpmN4

{
    "title": "test-title",
    "banner": "https://example.com/image-url",
    "des": "this is a short description",
    "content": {
        "blocks": [ 1, 2 ]
    },
    "tags": [ "tag1", "tag2" ]
}